# Generated by Django 3.2.14 on 2022-08-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kitchen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('pincode', models.IntegerField()),
                ('image1', models.ImageField(upload_to='tiffin/images')),
                ('image2', models.ImageField(upload_to='tiffin/images')),
                ('image3', models.ImageField(upload_to='tiffin/images', verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='tiffin_user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
