# Generated by Django 3.2.14 on 2022-08-02 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0002_auto_20220802_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sun', models.CharField(max_length=100)),
                ('mon', models.CharField(max_length=100)),
                ('tue', models.CharField(max_length=100)),
                ('wed', models.CharField(max_length=100)),
                ('thu', models.CharField(max_length=100)),
                ('fri', models.CharField(max_length=100)),
                ('sat', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default='Veg', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sun', models.CharField(max_length=100)),
                ('mon', models.CharField(max_length=100)),
                ('tue', models.CharField(max_length=100)),
                ('wed', models.CharField(max_length=100)),
                ('thu', models.CharField(max_length=100)),
                ('fri', models.CharField(max_length=100)),
                ('sat', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default='Veg', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sun', models.CharField(max_length=100)),
                ('mon', models.CharField(max_length=100)),
                ('tue', models.CharField(max_length=100)),
                ('wed', models.CharField(max_length=100)),
                ('thu', models.CharField(max_length=100)),
                ('fri', models.CharField(max_length=100)),
                ('sat', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default='Veg', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('breakfast', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tiffin.breakfast')),
                ('dinner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tiffin.dinner')),
                ('kitchen', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tiffin.kitchen')),
                ('lunch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tiffin.lunch')),
            ],
        ),
    ]
